# Generated by Django 4.2.7 on 2023-11-07 13:42

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateAgent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_no', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(limit_value=9, message='License number must be 9 characters.'), django.core.validators.MaxLengthValidator(limit_value=9, message='License number must be 9 characters.')])),
                ('telephone_no', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(limit_value=9, message='Telephone number must be 9 characters.'), django.core.validators.MaxLengthValidator(limit_value=9, message='Telephone number must be 9 characters.')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=255)),
                ('bathrooms', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('fireplaces', models.PositiveIntegerField()),
                ('parking_spaces', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('gone', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.realestateagent')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.state')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, verbose_name='image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
