# Generated by Django 4.2.6 on 2023-10-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
