# Generated by Django 4.2.6 on 2023-10-19 15:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_delete_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_url',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, verbose_name='image'),
        ),
    ]
