# Generated by Django 4.2.6 on 2023-10-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_images_image_url_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gone',
            field=models.BooleanField(default=False),
        ),
    ]
