# Generated by Django 4.2.6 on 2023-10-23 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_gone'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateagent',
            name='telephone_no',
            field=models.CharField(default=123456789, max_length=9, validators=[django.core.validators.MinLengthValidator(limit_value=9, message='Telephone number must be 9 characters.'), django.core.validators.MaxLengthValidator(limit_value=9, message='Telephone number must be 9 characters.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realestateagent',
            name='license_no',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(limit_value=9, message='License number must be 9 characters.'), django.core.validators.MaxLengthValidator(limit_value=9, message='License number must be 9 characters.')]),
        ),
    ]
